"""
Chat router — user-facing endpoints for the CortexCFO advisor.

Pipeline for /ask:
  1. If mode == "quick": try the FAQ matcher first. Good matches return
     instantly (no LLM call) with the user's own numbers interpolated.
  2. Otherwise (or on FAQ miss): hand off to ai_service.chat_with_ai
     with the provided mode. Quick mode → Haiku, Deep mode → Sonnet 4
     with extended thinking enabled.
  3. Response always carries a `source` field ("faq" | "ai") so the UI
     can render a subtle badge — helpful for us during tuning, and a
     small trust-signal for the user.

/feedback is log-based in v1. A future iteration will persist to DB
for analytics; for now the Render log viewer + grep is enough.
"""

from __future__ import annotations

import logging
from typing import Literal, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from app.middleware.auth import get_current_user
from app.models.user import User
from app.services.ai_service import chat_with_ai
from app.services.faq_service import try_faq_answer

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/chat", tags=["chat"])


class ChatMessage(BaseModel):
    role: str  # "user" or "ai"
    text: str


class ChatRequest(BaseModel):
    question: str
    analysis_result: dict  # The full analysis result from TB analysis
    conversation_history: list[ChatMessage] = []
    business_context: dict | None = None
    user_answers: dict | None = None  # Answers to AI questions: {question: answer}
    # Optional: "claude" | "gemini" | "groq". When omitted, Claude is tried
    # first with automatic fallback to Gemini and Groq on failure.
    provider: str | None = None
    # "quick" = Haiku, FAQ-first, snappy. "deep" = Sonnet 4 extended
    # thinking, slower but reflects real reasoning. Default quick so new
    # callers keep the fast UX without opting in.
    mode: Literal["quick", "deep"] = "quick"


class ChatResponse(BaseModel):
    response: str
    # "faq" = returned a seeded FAQ answer (near-zero latency, no LLM call).
    # "ai" = generated by the LLM provider chain.
    source: Literal["faq", "ai"]
    # Present when source == "faq" — lets us investigate bad matches
    # later. Safe to expose; it's just an internal id like "faq-xxx".
    faq_id: Optional[str] = None
    # Which mode the caller asked for (echoed for client-side UI state).
    mode: Literal["quick", "deep"] = "quick"


class AnswerQuestionRequest(BaseModel):
    question: str
    answer: str
    analysis_result: dict
    all_answers: dict = {}  # All previous Q&A pairs
    business_context: dict | None = None
    provider: str | None = None


class FeedbackRequest(BaseModel):
    question: str = Field(..., max_length=4000)
    response: str = Field(..., max_length=20000)
    helpful: bool
    # Optional free-text "what went wrong" when helpful == False.
    notes: Optional[str] = Field(None, max_length=2000)
    source: Optional[Literal["faq", "ai"]] = None
    faq_id: Optional[str] = None
    mode: Optional[Literal["quick", "deep"]] = None
    # The page the user was on — sent as the leading path for context.
    page: Optional[str] = Field(None, max_length=200)


@router.post("/ask", response_model=ChatResponse)
async def ask_ai(
    data: ChatRequest,
    current_user: User = Depends(get_current_user),
):
    """Chat with CortexAI about the financial analysis.

    Quick mode tries FAQ matching first (stdlib matcher, no LLM call);
    anything that doesn't clear the confidence threshold falls through
    to the LLM. Deep mode skips FAQ entirely — if the user opted in to
    Strategic Thinking they want the model, not a canned template.
    """
    if not data.question.strip():
        raise HTTPException(status_code=400, detail="Question is required")

    # Phase 2: FAQ-first for Quick mode only. Deep mode callers are
    # explicitly asking for thinking — don't intercept with a template.
    if data.mode == "quick":
        match = try_faq_answer(
            question=data.question,
            analysis_result=data.analysis_result,
            business_context=data.business_context,
        )
        if match:
            logger.info(
                "FAQ hit user=%s faq_id=%s score=%s mode=%s",
                current_user.id, match["faq_id"], match["score"], data.mode,
            )
            return ChatResponse(
                response=match["answer"],
                source="faq",
                faq_id=match["faq_id"],
                mode=data.mode,
            )

    history = [{"role": m.role, "text": m.text} for m in data.conversation_history]

    response = await chat_with_ai(
        question=data.question,
        analysis_result=data.analysis_result,
        conversation_history=history,
        business_context=data.business_context,
        user_answers=data.user_answers,
        provider=data.provider,
        mode=data.mode,
    )

    return ChatResponse(response=response, source="ai", mode=data.mode)


@router.post("/answer-question")
async def answer_question(
    data: AnswerQuestionRequest,
    current_user: User = Depends(get_current_user),
):
    """
    User answers one of the AI's clarifying questions.
    AI incorporates the answer and provides updated analysis.
    """
    all_answers = data.all_answers or {}
    all_answers[data.question] = data.answer

    prompt = f"""The management has answered the following question about their financials:

Question: {data.question}
Answer: {data.answer}

Based on this answer and the financial data, provide:
1. How this answer impacts the analysis
2. Any adjusted numbers or reclassifications needed
3. Any follow-up concerns or recommendations

Be specific and reference actual numbers from the data."""

    response = await chat_with_ai(
        question=prompt,
        analysis_result=data.analysis_result,
        business_context=data.business_context,
        user_answers=all_answers,
        provider=data.provider,
    )

    return {
        "response": response,
        "updated_answers": all_answers,
    }


@router.post("/feedback")
async def submit_feedback(
    data: FeedbackRequest,
    current_user: User = Depends(get_current_user),
):
    """Record a thumbs-up/down on an AI response.

    v1: log-based. Dumps a structured line to stdout so it shows up in
    Render's log viewer; we can grep/aggregate for weekly FAQ reviews.
    A future iteration will persist to a `chat_feedback` table once we
    have volume that's worth charting.
    """
    verdict = "helpful" if data.helpful else "NOT helpful"
    logger.info(
        "[CHAT_FEEDBACK] user=%s verdict=%s source=%s mode=%s faq_id=%s page=%s "
        "question=%r notes=%r",
        current_user.id,
        verdict,
        data.source,
        data.mode,
        data.faq_id,
        data.page,
        (data.question or "")[:500],
        (data.notes or "")[:500],
    )
    return {"ok": True}
