"""
Chat router — user-facing endpoints for the CortexCFO advisor.

Pipeline for /ask:
  1. If mode == "quick": try the FAQ matcher first. Good matches return
     instantly (no LLM call) with the user's own numbers interpolated.
  2. Otherwise (or on FAQ miss): hand off to ai_service.chat_with_ai
     with the provided mode. Quick mode → Haiku, Deep mode → Sonnet 4
     with extended thinking enabled.
  3. Response always carries a `source` field ("faq" | "ai") so the UI
     can render a subtle badge — helpful for us during tuning, and a
     small trust-signal for the user.

/feedback is log-based in v1. A future iteration will persist to DB
for analytics; for now the Render log viewer + grep is enough.
"""

from __future__ import annotations

import json
import logging
from typing import AsyncIterator, Literal, Optional

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from sqlalchemy import desc, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.middleware.auth import get_current_user
from app.models.chat_feedback import ChatFeedback
from app.models.user import User
from app.services.ai_service import chat_with_ai, stream_deep
from app.services.faq_service import try_faq_answer

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/chat", tags=["chat"])


class ChatMessage(BaseModel):
    role: str  # "user" or "ai"
    text: str


class ChatRequest(BaseModel):
    question: str
    analysis_result: dict  # The full analysis result from TB analysis
    conversation_history: list[ChatMessage] = []
    business_context: dict | None = None
    user_answers: dict | None = None  # Answers to AI questions: {question: answer}
    # Optional: "claude" | "gemini" | "groq". When omitted, Claude is tried
    # first with automatic fallback to Gemini and Groq on failure.
    provider: str | None = None
    # "quick" = Haiku, FAQ-first, snappy. "deep" = Sonnet 4 extended
    # thinking, slower but reflects real reasoning. Default quick so new
    # callers keep the fast UX without opting in.
    mode: Literal["quick", "deep"] = "quick"


class ChatResponse(BaseModel):
    response: str
    # "faq" = returned a seeded FAQ answer (near-zero latency, no LLM call).
    # "ai" = generated by the LLM provider chain.
    source: Literal["faq", "ai"]
    # Present when source == "faq" — lets us investigate bad matches
    # later. Safe to expose; it's just an internal id like "faq-xxx".
    faq_id: Optional[str] = None
    # Which mode the caller asked for (echoed for client-side UI state).
    mode: Literal["quick", "deep"] = "quick"


class AnswerQuestionRequest(BaseModel):
    question: str
    answer: str
    analysis_result: dict
    all_answers: dict = {}  # All previous Q&A pairs
    business_context: dict | None = None
    provider: str | None = None


class FeedbackRequest(BaseModel):
    question: str = Field(..., max_length=4000)
    response: str = Field(..., max_length=20000)
    helpful: bool
    # Optional free-text "what went wrong" when helpful == False.
    notes: Optional[str] = Field(None, max_length=2000)
    source: Optional[Literal["faq", "ai"]] = None
    faq_id: Optional[str] = None
    mode: Optional[Literal["quick", "deep"]] = None
    # The page the user was on — sent as the leading path for context.
    page: Optional[str] = Field(None, max_length=200)


@router.post("/ask", response_model=ChatResponse)
async def ask_ai(
    data: ChatRequest,
    current_user: User = Depends(get_current_user),
):
    """Chat with CortexAI about the financial analysis.

    Quick mode tries FAQ matching first (stdlib matcher, no LLM call);
    anything that doesn't clear the confidence threshold falls through
    to the LLM. Deep mode skips FAQ entirely — if the user opted in to
    Strategic Thinking they want the model, not a canned template.
    """
    if not data.question.strip():
        raise HTTPException(status_code=400, detail="Question is required")

    # Phase 2: FAQ-first for Quick mode only. Deep mode callers are
    # explicitly asking for thinking — don't intercept with a template.
    if data.mode == "quick":
        match = try_faq_answer(
            question=data.question,
            analysis_result=data.analysis_result,
            business_context=data.business_context,
        )
        if match:
            logger.info(
                "FAQ hit user=%s faq_id=%s score=%s mode=%s",
                current_user.id, match["faq_id"], match["score"], data.mode,
            )
            return ChatResponse(
                response=match["answer"],
                source="faq",
                faq_id=match["faq_id"],
                mode=data.mode,
            )

    history = [{"role": m.role, "text": m.text} for m in data.conversation_history]

    response = await chat_with_ai(
        question=data.question,
        analysis_result=data.analysis_result,
        conversation_history=history,
        business_context=data.business_context,
        user_answers=data.user_answers,
        provider=data.provider,
        mode=data.mode,
    )

    return ChatResponse(response=response, source="ai", mode=data.mode)


# ─── Streaming Deep mode (Phase 4.5) ────────────────────────────────

def _sse_format(event: str, data: dict) -> str:
    """Encode a dict as an SSE message. Keeps the wire format in one spot
    — easier to change to a framed JSON protocol later without touching
    the service layer."""
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


@router.post("/ask-stream")
async def ask_ai_stream(
    data: ChatRequest,
    current_user: User = Depends(get_current_user),
):
    """Streaming variant of /ask for Deep mode.

    Returns Server-Sent Events so the frontend can render thinking tokens
    live (latency-as-feature UX — founder SEES the reasoning happen).

    Event types in the stream:
      thinking  — partial reasoning chunk (Sonnet's extended-thinking
                  trace). Accumulate into a collapsible "Thinking" pane.
      response  — partial answer chunk. Append to the main reply bubble.
      done      — stream finished cleanly. Frontend can close the reader.
      error     — fatal; frontend should fall back to POST /ask.

    This endpoint is intentionally Deep-only. Quick mode stays on the
    regular /ask endpoint (JSON, FAQ-first). Mixing streaming into the
    FAQ path would be pointless — the answer is already local.
    """
    if not data.question.strip():
        raise HTTPException(status_code=400, detail="Question is required")
    if data.mode != "deep":
        raise HTTPException(
            status_code=400,
            detail="Streaming is only available in Deep mode. Use POST /ask for Quick.",
        )

    history = [{"role": m.role, "text": m.text} for m in data.conversation_history]

    async def event_stream() -> AsyncIterator[bytes]:
        try:
            async for chunk in stream_deep(
                question=data.question,
                analysis_result=data.analysis_result,
                conversation_history=history,
                business_context=data.business_context,
                user_answers=data.user_answers,
            ):
                evt_type = chunk.get("type", "error")
                payload: dict = {k: v for k, v in chunk.items() if k != "type"}
                yield _sse_format(evt_type, payload).encode("utf-8")
        except Exception as e:
            logger.exception("ask-stream generator crashed: %s", e)
            yield _sse_format("error", {"text": "Stream interrupted — please retry."}).encode("utf-8")

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            # Disable buffering at any proxy in front of us (e.g. Vercel
            # edge, CDN layers) so tokens arrive as emitted, not after
            # the entire response completes.
            "Cache-Control": "no-cache, no-transform",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


@router.post("/answer-question")
async def answer_question(
    data: AnswerQuestionRequest,
    current_user: User = Depends(get_current_user),
):
    """
    User answers one of the AI's clarifying questions.
    AI incorporates the answer and provides updated analysis.
    """
    all_answers = data.all_answers or {}
    all_answers[data.question] = data.answer

    prompt = f"""The management has answered the following question about their financials:

Question: {data.question}
Answer: {data.answer}

Based on this answer and the financial data, provide:
1. How this answer impacts the analysis
2. Any adjusted numbers or reclassifications needed
3. Any follow-up concerns or recommendations

Be specific and reference actual numbers from the data."""

    response = await chat_with_ai(
        question=prompt,
        analysis_result=data.analysis_result,
        business_context=data.business_context,
        user_answers=all_answers,
        provider=data.provider,
    )

    return {
        "response": response,
        "updated_answers": all_answers,
    }


@router.post("/feedback")
async def submit_feedback(
    data: FeedbackRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Record a thumbs-up/down on an AI response.

    Phase 3.5: persists to the `chat_feedback` table so we can power
    the admin dashboard and drive FAQ corpus expansion from real user
    pain points. We keep the structured log line too — if the DB write
    fails we still want forensic evidence of the vote.
    """
    verdict = "helpful" if data.helpful else "NOT helpful"
    logger.info(
        "[CHAT_FEEDBACK] user=%s verdict=%s source=%s mode=%s faq_id=%s page=%s "
        "question=%r notes=%r",
        current_user.id,
        verdict,
        data.source,
        data.mode,
        data.faq_id,
        data.page,
        (data.question or "")[:500],
        (data.notes or "")[:500],
    )

    row = ChatFeedback(
        user_id=current_user.id,
        question=data.question,
        response=data.response,
        helpful=data.helpful,
        notes=data.notes,
        source=data.source,
        faq_id=data.faq_id,
        mode=data.mode,
        page=data.page,
    )
    db.add(row)
    try:
        await db.commit()
    except Exception as e:
        # Never surface a DB commit failure to the user — the vote was
        # logged to stdout above; losing the row is fine for v1.
        logger.exception("Failed to persist chat_feedback: %s", e)
        await db.rollback()

    return {"ok": True}


# ─── Stats (Phase 3.5 dashboard) ────────────────────────────────────


class FeedbackStats(BaseModel):
    total: int
    helpful_count: int
    unhelpful_count: int
    # Helpful-rate as a 0-100 integer (percent). Returned pre-computed so
    # the frontend doesn't divide-by-zero on an empty corpus.
    helpful_rate_pct: int
    # Split by mode + source so we can see "is Deep mode earning its
    # ~10x latency?" and "are FAQ hits better-received than AI?"
    by_mode: dict[str, "FeedbackBreakdown"]
    by_source: dict[str, "FeedbackBreakdown"]
    # Top N downvoted FAQ ids — direct list of "templates to rework".
    top_downvoted_faqs: list["DownvotedFaq"]
    # Recent downvote samples (question text + short response snippet).
    # Capped at 20. Useful for curating new FAQs.
    recent_downvotes: list["DownvoteSample"]


class FeedbackBreakdown(BaseModel):
    total: int
    helpful: int
    unhelpful: int
    helpful_rate_pct: int


class DownvotedFaq(BaseModel):
    faq_id: str
    downvote_count: int


class DownvoteSample(BaseModel):
    created_at: str
    question: str
    response_snippet: str
    source: str | None
    mode: str | None
    page: str | None
    faq_id: str | None


def _rate(total: int, helpful: int) -> int:
    if total <= 0:
        return 0
    return round((helpful / total) * 100)


@router.get("/feedback/stats", response_model=FeedbackStats)
async def feedback_stats(
    scope: Literal["mine", "all"] = "mine",
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Return aggregate feedback stats.

    `scope=mine` (default): just the current user's feedback. Safe for
    any authenticated user to call — privacy-preserving.

    `scope=all`: platform-wide. Currently also allowed for any
    authenticated user since we're single-tenant / founder-mode. When
    we add roles we'll gate this on `current_user.is_admin` or similar.
    """
    q = select(ChatFeedback)
    if scope == "mine":
        q = q.where(ChatFeedback.user_id == current_user.id)

    # Totals + helpful/unhelpful split in one query each. Two queries
    # beats loading every row into memory.
    total_q = select(func.count()).select_from(q.subquery())
    helpful_q = select(func.count()).select_from(
        q.where(ChatFeedback.helpful.is_(True)).subquery()
    )
    unhelpful_q = select(func.count()).select_from(
        q.where(ChatFeedback.helpful.is_(False)).subquery()
    )

    total = (await db.execute(total_q)).scalar_one() or 0
    helpful = (await db.execute(helpful_q)).scalar_one() or 0
    unhelpful = (await db.execute(unhelpful_q)).scalar_one() or 0

    # Breakdown by mode
    by_mode_rows = (
        await db.execute(
            select(
                ChatFeedback.mode,
                ChatFeedback.helpful,
                func.count().label("cnt"),
            )
            .where(
                ChatFeedback.user_id == current_user.id
                if scope == "mine"
                else True  # trivially True for scope=all
            )
            .group_by(ChatFeedback.mode, ChatFeedback.helpful)
        )
    ).all()

    by_mode: dict[str, FeedbackBreakdown] = {}
    for mode_val, is_helpful, cnt in by_mode_rows:
        key = mode_val or "unknown"
        slot = by_mode.setdefault(
            key, FeedbackBreakdown(total=0, helpful=0, unhelpful=0, helpful_rate_pct=0)
        )
        slot.total += cnt
        if is_helpful:
            slot.helpful += cnt
        else:
            slot.unhelpful += cnt
    for slot in by_mode.values():
        slot.helpful_rate_pct = _rate(slot.total, slot.helpful)

    # Breakdown by source
    by_source_rows = (
        await db.execute(
            select(
                ChatFeedback.source,
                ChatFeedback.helpful,
                func.count().label("cnt"),
            )
            .where(
                ChatFeedback.user_id == current_user.id
                if scope == "mine"
                else True
            )
            .group_by(ChatFeedback.source, ChatFeedback.helpful)
        )
    ).all()

    by_source: dict[str, FeedbackBreakdown] = {}
    for source_val, is_helpful, cnt in by_source_rows:
        key = source_val or "unknown"
        slot = by_source.setdefault(
            key, FeedbackBreakdown(total=0, helpful=0, unhelpful=0, helpful_rate_pct=0)
        )
        slot.total += cnt
        if is_helpful:
            slot.helpful += cnt
        else:
            slot.unhelpful += cnt
    for slot in by_source.values():
        slot.helpful_rate_pct = _rate(slot.total, slot.helpful)

    # Top 10 downvoted FAQs (faq_id IS NOT NULL, helpful = False)
    top_faqs_rows = (
        await db.execute(
            select(
                ChatFeedback.faq_id,
                func.count().label("cnt"),
            )
            .where(
                ChatFeedback.faq_id.isnot(None),
                ChatFeedback.helpful.is_(False),
                ChatFeedback.user_id == current_user.id
                if scope == "mine"
                else True,
            )
            .group_by(ChatFeedback.faq_id)
            .order_by(desc("cnt"))
            .limit(10)
        )
    ).all()
    top_downvoted_faqs = [
        DownvotedFaq(faq_id=faq_id or "unknown", downvote_count=cnt)
        for faq_id, cnt in top_faqs_rows
    ]

    # Recent downvotes (sample for FAQ curation)
    recent_rows = (
        await db.execute(
            select(ChatFeedback)
            .where(
                ChatFeedback.helpful.is_(False),
                ChatFeedback.user_id == current_user.id
                if scope == "mine"
                else True,
            )
            .order_by(desc(ChatFeedback.created_at))
            .limit(20)
        )
    ).scalars().all()

    recent_downvotes = [
        DownvoteSample(
            created_at=r.created_at.isoformat() if r.created_at else "",
            question=r.question,
            response_snippet=(r.response[:280] + "…") if len(r.response) > 280 else r.response,
            source=r.source,
            mode=r.mode,
            page=r.page,
            faq_id=r.faq_id,
        )
        for r in recent_rows
    ]

    return FeedbackStats(
        total=total,
        helpful_count=helpful,
        unhelpful_count=unhelpful,
        helpful_rate_pct=_rate(total, helpful),
        by_mode=by_mode,
        by_source=by_source,
        top_downvoted_faqs=top_downvoted_faqs,
        recent_downvotes=recent_downvotes,
    )
