"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { Activity } from "lucide-react";

export default function TermsPage() {
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    const handleScroll = () => setScrollY(window.scrollY);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const sections = [
    {
      title: "1. Agreement to Terms",
      content: "By accessing or using the CortexCFO platform, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using the platform. These terms apply to all users, including individual users, businesses, and enterprise clients. CortexCFO reserves the right to update these terms at any time, and continued use of the platform constitutes acceptance of any modifications."
    },
    {
      title: "2. Use of Service",
      content: "CortexCFO provides AI-powered financial analysis, scenario modeling, and reporting tools. You may use the platform only for lawful purposes and in accordance with these terms. You agree not to use the platform to upload fraudulent financial data, attempt to reverse-engineer our AI models, or resell access without authorization. You are responsible for maintaining the confidentiality of your account credentials. CortexCFO is a decision-support tool and does not constitute financial, legal, or tax advice."
    },
    {
      title: "3. Accounts & Access",
      content: "You must provide accurate, current, and complete information when creating an account. Each account is for a single user or authorized organization. You are responsible for all activity under your account. You must notify us immediately of any unauthorized access. We reserve the right to suspend or terminate accounts that violate these terms, engage in fraudulent activity, or remain inactive for more than 12 consecutive months."
    },
    {
      title: "4. Intellectual Property",
      content: "The CortexCFO platform, including its software, AI models, algorithms, designs, documentation, and branding, is the exclusive property of CortexCFO Financial Intelligence Pvt. Ltd. You retain full ownership of all financial data you upload to the platform. Insights, reports, and analyses generated by CortexCFO based on your data are licensed to you for your internal business use. You may not copy, modify, distribute, or create derivative works of any part of the platform without prior written consent."
    },
    {
      title: "5. Payment Terms",
      content: "Paid plans are billed monthly or annually as selected at the time of subscription. All fees are quoted in Indian Rupees (INR) and are exclusive of applicable taxes (GST). Refunds are available within 14 days of initial purchase for annual plans. We reserve the right to change pricing with 30 days advance notice. Failure to pay may result in service suspension. Free tier users are subject to usage limits as described on our pricing page."
    },
    {
      title: "6. Limitation of Liability",
      content: "CortexCFO provides the platform on an \"as is\" and \"as available\" basis. We do not guarantee that the platform will be uninterrupted, error-free, or that any financial analysis will be complete or accurate in all cases. To the maximum extent permitted by law, CortexCFO shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities. Our total liability for any claim shall not exceed the amount you paid for the platform in the 12 months preceding the claim."
    },
    {
      title: "7. Termination",
      content: "Either party may terminate this agreement at any time. You may cancel your subscription through your account settings. Upon termination, your access to the platform will cease and your data will be retained for 90 days before permanent deletion, unless you request earlier deletion. Sections relating to intellectual property, limitation of liability, and governing law shall survive termination."
    },
    {
      title: "8. Governing Law",
      content: "These terms are governed by and construed in accordance with the laws of India. Any disputes arising from these terms or the use of the platform shall be subject to the exclusive jurisdiction of the courts in Bangalore, Karnataka, India. If any provision of these terms is found to be unenforceable, the remaining provisions shall continue in full force and effect."
    },
    {
      title: "9. Contact",
      content: "For questions about these Terms of Service, contact us at legal@cortexcfo.in or write to: CortexCFO Financial Intelligence Pvt. Ltd., WeWork Embassy Golf Links, Bangalore, Karnataka 560071, India."
    },
  ];

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white overflow-hidden">
      {/* Navigation */}
      <nav className={`fixed top-0 w-full z-50 transition-all duration-500 ${
        scrollY > 50
          ? "bg-[#0a0a0a]/90 backdrop-blur-xl border-b border-white/5"
          : "bg-transparent"
      }`}>
        <div className="max-w-[1400px] mx-auto px-8 h-[72px] flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-emerald-500 flex items-center justify-center">
              <Activity className="w-4.5 h-4.5 text-white" />
            </div>
            <span className="text-[20px] font-bold tracking-[-0.03em]">CortexCFO</span>
          </Link>
          <div className="hidden md:flex items-center gap-10 text-[13.5px] text-white/50 font-medium">
            <Link href="/#platform" className="hover:text-white transition-colors duration-300">Platform</Link>
            <Link href="/#customers" className="hover:text-white transition-colors duration-300">Customers</Link>
            <Link href="/#pricing" className="hover:text-white transition-colors duration-300">Pricing</Link>
            <Link href="/about" className="hover:text-white transition-colors duration-300">About</Link>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/login" className="text-[13.5px] text-[#666] hover:text-white transition-colors font-medium">Log in</Link>
            <Link href="/signup" className="text-[13.5px] bg-emerald-500 text-white font-medium px-4 py-2 rounded-lg hover:bg-emerald-400 transition-all">
              Request access
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative bg-[#1a1a17] text-white overflow-hidden">
        <div className="absolute inset-0 opacity-[0.03]" style={{
          backgroundImage: "linear-gradient(rgba(255,255,255,0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.1) 1px, transparent 1px)",
          backgroundSize: "60px 60px"
        }} />
        <div className="relative z-10 max-w-[1400px] mx-auto px-8 pt-40 pb-20 w-full">
          <div className="max-w-[700px] mx-auto text-center">
            <h1 className="text-[clamp(2.5rem,5.5vw,4rem)] font-light tracking-[-0.04em] leading-[1.1] mb-6">
              Terms of <span className="italic font-normal">Service</span>
            </h1>
            <p className="text-[15px] text-white/40">Last updated: April 2026</p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-20 px-8">
        <div className="max-w-[760px] mx-auto">
          <p className="text-[16px] text-white/40 leading-[1.8] mb-12">
            Please read these Terms of Service carefully before using the CortexCFO platform.
            These terms govern your access to and use of CortexCFO and all related services
            provided by CortexCFO Financial Intelligence Pvt. Ltd.
          </p>
          <div className="space-y-10">
            {sections.map(section => (
              <div key={section.title}>
                <h2 className="text-[20px] font-semibold tracking-[-0.02em] mb-4">{section.title}</h2>
                <p className="text-[15px] text-white/40 leading-[1.8]">{section.content}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Related links */}
      <section className="py-16 px-8 bg-[#080808] border-t border-white/5">
        <div className="max-w-[760px] mx-auto flex flex-col sm:flex-row items-center justify-center gap-6">
          <Link href="/privacy" className="text-[14px] text-white/40 hover:text-white transition-colors font-medium underline underline-offset-4">
            Privacy Policy
          </Link>
          <span className="text-white/10 hidden sm:inline">|</span>
          <Link href="/about" className="text-[14px] text-white/40 hover:text-white transition-colors font-medium underline underline-offset-4">
            About CortexCFO
          </Link>
          <span className="text-white/10 hidden sm:inline">|</span>
          <Link href="/" className="text-[14px] text-white/40 hover:text-white transition-colors font-medium underline underline-offset-4">
            Back to Home
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-[#1a1a17] text-white border-t border-white/[0.06] py-16 px-8">
        <div className="max-w-[1200px] mx-auto">
          <div className="grid md:grid-cols-5 gap-12 mb-16">
            <div className="md:col-span-2">
              <div className="flex items-center gap-2.5 mb-5">
                <div className="w-8 h-8 rounded-xl bg-white/10 flex items-center justify-center">
                  <Activity className="w-4 h-4" />
                </div>
                <span className="text-[18px] font-bold tracking-[-0.02em]">CortexCFO</span>
              </div>
              <p className="text-[13px] text-white/30 leading-[1.8] max-w-xs">
                AI-powered financial intelligence platform for Indian businesses.
                Continuous QoE, scenario modeling, and prescriptive insights.
              </p>
            </div>
            {[
              { title: "Product", links: [{ label: "Dashboard", href: "/#platform" }, { label: "TB Analysis", href: "/#platform" }, { label: "Scenarios", href: "/#platform" }, { label: "QoE Center", href: "/#platform" }, { label: "Integrations", href: "/#platform" }] },
              { title: "Company", links: [{ label: "About", href: "/about" }, { label: "Careers", href: "#" }, { label: "Blog", href: "#" }, { label: "Press", href: "#" }, { label: "Contact", href: "#" }] },
              { title: "Legal", links: [{ label: "Privacy", href: "/privacy" }, { label: "Terms", href: "/terms" }, { label: "Security", href: "#" }, { label: "GDPR", href: "#" }, { label: "DPDP", href: "#" }] },
            ].map(col => (
              <div key={col.title}>
                <p className="text-[12px] font-semibold text-white/50 uppercase tracking-wider mb-4">{col.title}</p>
                <ul className="space-y-2.5">
                  {col.links.map(link => (
                    <li key={link.label}>
                      <Link href={link.href} className="text-[13px] text-white/30 hover:text-white/60 transition-colors">{link.label}</Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          <div className="border-t border-white/[0.06] pt-8 flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-[11px] text-white/20">&copy; 2026 CortexCFO Financial Intelligence Pvt. Ltd. All rights reserved.</p>
            <div className="flex items-center gap-6 text-[12px] text-white/20">
              <a href="#" className="hover:text-white/40">Twitter</a>
              <a href="#" className="hover:text-white/40">LinkedIn</a>
              <a href="#" className="hover:text-white/40">GitHub</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
